ablog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('theblog.urls','theblog'), namespace='posts')),
    #Contiene un sistema basico de manejo de sesiones (Login, logouth, crear, modificar perfil)
    path('user',include('django.contrib.auth.urls')),
    #Si hay una url adicional va acá a buscarla
    path('user',include(('user.urls','user'), namespace='user')),
]

theblog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView

urlpatterns = [
    path('list', HomeView.as_view(), name='list'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='articleDetail'),
    path('addpost', AddPostView.as_view(), name='create_post'),
    path('edit/<int:pk>', UpdatePostView.as_view(), name='updatePost'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='deletePost'),
]

user/urls.py
from django.urls import path
from user import views

urlpatterns = [
    path('register', views.UserRegisterView.as_view(), name='register'),
    path('login', views.LoginUserView.as_view(), name='login'),
    path('logout', views.logoutUserView, name='logout')
]

theblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date

class Post(models.Model):
    title = models.CharField(max_length=255)
    #Al conectar con modelo User, se puede preguntar cualquier cosa de ciho objeto
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title_tag = models.CharField(max_length=255)
    body = models.TextField()
    post_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        print(self.id)
        return '/article/%s' %(self.id)

user/models.py
from django.db import models

# Create your models here.

theblog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from theblog.models import Post
from theblog.form import CreateForm
from django.urls import reverse_lazy
from django.urls import reverse

class HomeView(ListView):
    model = Post
    template_name = 'post/home.html'
    ordering = ['-post_date']

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'post/article_details.html'

class AddPostView(CreateView):
    template_name = 'post/addpost.html'
    form_class = CreateForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class UpdatePostView(UpdateView):
    model = Post
    template_name = 'post/updatepost.html'
    fields = ['title','title_tag','body']

class DeletePostView(DeleteView):
    template_name = 'post/deletepost.html'
    model = Post
    reverse_lazy = 'list'

user/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views, logout
from django.shortcuts import redirect
from django.urls import reverse_lazy

class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('user:login')
    template_name = 'user/register.html'


class LoginUserView(views.LoginView):
    template_name = 'user/login.html'
    success_url = 'theblog:list'

def logoutUserView(request):
    logout(request)
    return redirect ('user:login')

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

        {% block head_content %}{% endblock %}
    </head>
    <body>
        {% include "nav.html" %}
        <br/>
        <div class="container">
            {% block content %}{% endblock  %}
        </div>
        

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        -->
    </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Inicio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if request.user.is_authenticated %}
               <a href="#" class="btn btn-primary">Bienvenido {{ request.user.username }}</a>
          {% else %}
              <a href="{% url 'user:login' %}" class="btn btn-primary">Iniciar sesion</a>
        </li>
        <li class="nav-item">
              <p class="text-muted">Usuario nuevo? Registrese <a class="badge bg-success" href="{% url 'user:register' %}">aquí</a></p>
          {% endif %}

        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'theblog:list' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'theblog:create_post' %}">Crear Post</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'user:logout' %}" class="btn btn-primary">Cerrar sesion</a>
          </li>
        {% endif %}

      </ul>
      <form class="d-flex">

      </form>
    </div>
  </div>
</nav>

templates/post/addpost.html
{% extends 'base.html' %}

{% block content %}
    <title>Añadir un post</title>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-secondary">
    </form>
{% endblock  %}

templates/post/article_details.html
{% extends 'base.html' %}

{% block head_content %}
    <title>{{ post.title }} Post</title>
{% endblock  %}


{% block content %}
    <h1>{{ post.title }}</h1>
    {# Accediendo a los datos de la relacion #}
    <small>By: {{ post.author.first_name }} {{ post.author.last_name }} - {{ post.post_date }}</small>
    <a class="badge bg-warning text-dark" href='{% url 'theblog:updatePost'  post.pk %}'>Editar</a>
    <a class="badge bg-danger text-dark" href='{% url 'theblog:deletePost'  post.pk %}'>Eliminar</a><br/>
    <hr>
    {{ post.body }}

    <br/><a href="{% url 'theblog:list' %}" class="btn btn-secondary">Back<a>
{% endblock  %}

templates/post/deletepost.html
{% extends 'base.html' %}
{% block head_content %}
    <title>Eliminar un post</title>
{% endblock  %}
{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">
            Está seguro de eliminar el post titulado: {{ post.title }} ?
        </div>
        <input type="submit" value="Eliminar" class="btn btn-secondary">
    </form>
{% endblock  %}

templates/post/home.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Home</title>
{% endblock  %}

{% block content %}
    <h1>Posts</h1>
    {% for post in object_list %}
        <li><a href="{% url 'theblog:articleDetail' post.pk %}">{{ post.title }}</a> - {{ post.author }} - Creado el {{ post.post_date }}
        <a class="badge bg-warning text-dark" href='{% url 'theblog:updatePost'  post.pk %}'>Editar</a>
        <a class="badge bg-danger text-dark" href='{% url 'theblog:deletePost'  post.pk %}'>Eliminar</a></br>
        {{ post.body }}  </li>
    {% endfor %}
{% endblock  %}

templates/post/updatepost.html
{% extends 'base.html' %}
{% block head_content %}
    <title>Añadir un post</title>
{% endblock  %}
{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Actualizar" class="btn btn-secondary">
    </form>
{% endblock  %}

templates/user/login.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Login</title>
{% endblock  %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Iniciar" class="btn btn-primary">
    </form>

{% endblock  %}

templates/user/register.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Registrate</title>
{% endblock  %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Registrarse" class="btn btn-primary">
    </form>

{% endblock  %}

theblog/templates/article_details.html
{% extends 'base.html' %}

{% block head_content %}
    <title>{{ post.title }} Post</title>
{% endblock  %}


{% block content %}
    <h1>{{ post.title }}</h1>
    {# Accediendo a los datos de la relacion #}
    <small>By: {{ post.author.first_name }} {{post.author.last_name }}</small>
    <a class="badge bg-warning text-dark" href='{% url 'theblog:updatePost'  post.pk %}'>Editar</a>
    <a class="badge bg-danger text-dark" href='{% url 'theblog:deletePost'  post.pk %}'>Eliminar</a><br/>
    <hr>
    {{ post.body }}

    <br/><a href="{% url 'theblog:list' %}" class="btn btn-secondary">Back<a>
{% endblock  %}

theblog/templates/home.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Home</title>
{% endblock  %}

{% block content %}
    <h1>Posts</h1>
    {% for post in object_list %}
        <li><a href="{% url 'theblog:articleDetail' post.pk %}">{{ post.title }}</a> - {{ post.author }} 
        <a class="badge bg-warning text-dark" href='{% url 'theblog:updatePost'  post.pk %}'>Editar</a>   
        <a class="badge bg-danger text-dark" href='{% url 'theblog:deletePost'  post.pk %}'>Eliminar</a></br>
        {{ post.body }}  </li>
    {% endfor %}
{% endblock  %}

theblog/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Inicio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'theblog:list' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'theblog:create_post' %}">Crear Post</a>
        </li>
      </ul>
      <form class="d-flex">
        
      </form>
    </div>
  </div>
</nav>